find_program(NET_QUIC_AR ar REQUIRED)
find_program(NET_QUIC_RANLIB ranlib REQUIRED)
set(CMAKE_AR "${NET_QUIC_AR}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${NET_QUIC_RANLIB}" CACHE FILEPATH "" FORCE)
